### PR TITLE
Feature: Add season filtering into get_league

### PR DESCRIPTION
**Pull request by cosminpm**
### Description

Add season filtering into the `get_league` method. 

### Checklist

- [X] Code compiles correctly
- [X] Created tests which fail without the change (if applicable)
- [X] All lint and unit tests passing
- [X] Extended the README / documentation, if necessary

### Additional Comments

I have added these filter so we can filter by season.

### CODE REVIEW

**Comment by bgrnwd** [comment]
@cosminpm Thanks for the PR!

Looks like there are some linting errors. Mind taking care of those and then adding a test case for the new functionality?

**Comment by cosminpm** [comment]
@bgrnwd Yes, I will do it when I have some time, sorry for not checking the linting, my bad 😞

**Comment by bgrnwd** [comment]
No worries! We should also bump the patch number of `VERSION` in `client.py`

**Comment by cosminpm** [comment]
Hello @bgrnwd feel free to review. I added some small general improvements. 

By the way I think it would be nice to have the requirements of the project for future iterations.

**Comment by cosminpm** [comment]
Hello @bgrnwd I forgot to update the version number, can you do it?

**Comment by bgrnwd** [comment]
Yep, I will do it and push a version out

**Pull request merged**
